name: Deploy to CloudPanel

on:
  push:
    branches: [ main ]  # change if you deploy from another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then
            npm ci
          fi

      - name: Build project (skip if purely static)
        run: |
          if [ -f package.json ]; then
            npm run build || true
          fi

      - name: Prepare deployment artifact
        run: |
          rm -rf artifact && mkdir artifact
          # Prefer common build dirs; fallback to project root for plain static sites
          if [ -d dist ]; then
            cp -r dist/* artifact/
          elif [ -d out ]; then
            cp -r out/* artifact/
          else
            shopt -s dotglob
            cp -r * artifact/
            # remove repo-only files
            rm -rf artifact/.git artifact/.github || true
          fi

      - name: Add server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}   # 31.97.100.153
          SSH_PORT: ${{ secrets.SSH_PORT }}   # 22

      - name: Deploy via rsync over SSH
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete
          path: artifact/
          remote_path: /home/cloudpanel/htdocs/first.projectpartyproductions.com
          remote_host: ${{ secrets.SSH_HOST }}   # 31.97.100.153
          remote_user: ${{ secrets.SSH_USER }}   # deploy
          remote_port: ${{ secrets.SSH_PORT }}   # 22
          remote_key: ${{ secrets.SSH_KEY }}     # your OpenSSH private key block
